application: androidsoundappproject
version: alpha004
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css 
  
- url: /inc
  static_dir: inc

- url: /
  script: index.php

- url: /server
  script: server.php